---
  - name: Installing tomcat
    hosts: tomcat-client
    tasks:
    - name: Create the user
      become: yes
      user:
        name: tomcat
        state: present
    - name: Create a Directory /opt/tomcat
      become: yes
      file:
        path: /opt/tomcat
        state: directory
        mode: 0755
        owner: tomcat
        group: tomcat
    - name: Update the System Packages
      apt:
        upgrade: yes
        update_cache: yes
    - name: Install JAVA
      apt:
        name: default-jdk
        state: present
    - name: Download foo.conf
      ansible.builtin.get_url:
        url: wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
        dest: /tmp
        mode: '0440'